version: 2.1
description: Cloud Native Buildpacks Sample

orbs:
  buildpacks: jkutner/buildpacks@0.0.1

workflows:
  version: 2.1
  main:
    jobs:
      - buildpack/build:
          image-name: myimage
          builder: heroku/buildpacks:18
