version: 2.1
description: Cloud Native Buildpacks Sample

orbs:
  buildpacks: jkutner/buildpacks

workflows:
  version: 2.1
  main:
    jobs:
      - buildpacks/build:
          image-name: myimage
          builder: heroku/buildpacks:18
