version: 2.1
description: Cloud Native Buildpacks Sample

orbs:
  buildpacks: jkutner/buildpacks@dev:master

workflows:
  version: 2.1
  main:
    jobs:
      - buildpacks/build:
          image-name: myimage
          image-file: myimage.tgz
          builder: heroku/buildpacks:18
          buildpack: heroku/nodejs
      - publish:
          requires:
            - buildpacks/build

jobs:
  publish:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            docker load -i /tmp/workspace/images/myimage.tgz
            docker images