version: 2.1
description: Cloud Native Buildpacks Sample

orbs:
  buildpacks:
    jobs:
      build:
        description: "Build OCI Image"
        machine: true
        parameters:
          image-name:
            type: string
          builder:
            type: string
        steps:
          - install-pack
          - checkout
          - pack-build:
              image-name: << parameters.image-name >>
              builder: << parameters.builder >>
          - save-image:
              image-name: << parameters.image-name >>
    commands:
      save-image:
        description: "Save image"
        parameters:
          image-name:
            type: string
        steps:
          - run: mkdir -p build
          - run: docker save -o build/image.tgz << parameters.image-name >>
          - persist_to_workspace:
              root: .
              paths:
                - build

      pack-build:
        description: "Run pack build"
        parameters:
          image-name:
            type: string
          builder:
            type: string
        steps:
          - restore_cache:
              key: pack-cache-<< parameters.image-name >>-<< parameters.builder >>-{{ arch }}
          - run: pack build << parameters.image-name >> --builder << parameters.builder >>
          - save_cache:
              key: pack-cache-<< parameters.image-name >>-<< parameters.builder >>-{{ arch }}-{{ epoch }}
              paths:
                - /var/lib/docker/volumes/
      install-pack:
        description: "Setup and install pack"
        parameters:
          install-dir:
            default: ~/bin
            description: |
              Directory in which to install Pack binary
            type: string
          version:
            type: string
            default: 0.5.0
        steps:
          - run:
              name: "Setup and install pack"
              command: |
                mkdir -p << parameters.install-dir >>
                curl -L "https://github.com/buildpack/pack/releases/download/v<< parameters.version >>/pack-v<< parameters.version >>-linux.tgz" | tar xzm -C << parameters.install-dir >>
                export PATH="$PATH:<< parameters.install-dir >>"
                mkdir -p ~/.docker/
                if [ ! -f ~/.docker/config.json ]; then
                  echo "{}" > ~/.docker/config.json
                fi

workflows:
  version: 2.1
  main:
    jobs:
      - buildpacks/build:
          image-name: myimage
          builder: heroku/buildpacks:18
      - publish:
          requires:
            - buildpacks/build

jobs:
  publish:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            docker load -i /tmp/workspace/build/image.tgz
            docker images