version: 2.1
description: Cloud Native Buildpacks Sample

orbs:
  buildpacks: jkutner/buildpacks@0.0.3

workflows:
  version: 2.1
  main:
    jobs:
      - buildpacks/build:
          image-name: myimage
          builder: heroku/buildpacks:18
      - publish

jobs:
  publish:
    machine:
      docker_layer_caching: true
      enabled: true
      image: ubuntu-1604:201903-01
    steps:
      - docker images